# Example setup file
# .env-file contains some variables example: ${FOOBAR}
version: "3.8"

services:
    web:
        image: nginx:1.9.1 # Latest
        #image: nginx:1.7 # oldest available
        ports:
            - "8080:80"
        volumes:
            - ./src/site:/site
            - ./config/nginx.site.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - db_dict
            - db_log
            - db_user
    php:
        build:
            context: .
            dockerfile: Dockerfile-php7-fpm-mysql
        volumes:
            - ./src/site:/site
            - ./config/php.log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
            #- ./config/php.ini:/usr/local/etc/php/php.ini
## Place your own PHP.INI file in PHP directory and uncomment the line above
        depends_on: 
            - db_dict
            - db_log
            - db_user

## Databases
    db_log:
        image: mariadb:${MARIADB_VER_LOG} # 5.5.46 / oldest available
        restart: always
        volumes:
            - ./mariadb/log:/var/lib/mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

    db_user:
        image: mariadb:${MARIADB_VER_USER} # 10.5.4 / Latest
        restart: always
        volumes:
            - ./mariadb/user:/var/lib/mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

    db_dict:
        image: mariadb:${MARIADB_VER_DICT} # 10.5.4 / Latest
        restart: always
        volumes:
            - ./mariadb/dict:/var/lib/mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
## PhpMyAdmin 
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:${PMA_VER} # 5.0.2 / Latest
        #image: phpmyadmin/phpmyadmin:4.5.3.1-1 # oldest available
        ports:
            - "7000:80"
        environment: 
            - PMA_ARBITRARY=1
            - PMA_HOSTS=db_dict,db_log,db_user
        depends_on: 
            - db_dict
            - db_log
            - db_user